//! `verification`'s pieces: the key that overrides each and the piece it
//! is. Generated from one table with the config entries.

use config::settings as keys;
use config::settings::Words;

pub(super) fn judge() -> Vec<(Words, verification::Piece)> {
    vec![
        (
            keys::PROMPT_JUDGE_OPENING,
            verification::pieces::JUDGE_OPENING,
        ),
        (
            keys::PROMPT_JUDGE_QUESTION,
            verification::pieces::JUDGE_QUESTION,
        ),
        (
            keys::PROMPT_JUDGE_ANSWER,
            verification::pieces::JUDGE_ANSWER,
        ),
        (
            keys::PROMPT_JUDGE_REQUEST,
            verification::pieces::JUDGE_REQUEST,
        ),
        (
            keys::PROMPT_JUDGE_REQUEST_DONE_WHEN,
            verification::pieces::JUDGE_REQUEST_DONE_WHEN,
        ),
        (
            keys::PROMPT_JUDGE_READABLE,
            verification::pieces::JUDGE_READABLE,
        ),
        (
            keys::PROMPT_JUDGE_STANDING,
            verification::pieces::JUDGE_STANDING,
        ),
        (
            keys::PROMPT_JUDGE_STANDING_UNREADABLE,
            verification::pieces::JUDGE_STANDING_UNREADABLE,
        ),
        (
            keys::PROMPT_JUDGE_STANDING_CUT,
            verification::pieces::JUDGE_STANDING_CUT,
        ),
        (
            keys::PROMPT_JUDGE_CHECKS_RAN,
            verification::pieces::JUDGE_CHECKS_RAN,
        ),
        (
            keys::PROMPT_JUDGE_PRINTED,
            verification::pieces::JUDGE_PRINTED,
        ),
        (
            keys::PROMPT_JUDGE_PRINTED_TAIL,
            verification::pieces::JUDGE_PRINTED_TAIL,
        ),
        (
            keys::PROMPT_JUDGE_DELIVERABLE,
            verification::pieces::JUDGE_DELIVERABLE,
        ),
        (keys::PROMPT_JUDGE_PLAN, verification::pieces::JUDGE_PLAN),
        (
            keys::PROMPT_JUDGE_SUMMARY_AFTER,
            verification::pieces::JUDGE_SUMMARY_AFTER,
        ),
        (
            keys::PROMPT_JUDGE_SUMMARY,
            verification::pieces::JUDGE_SUMMARY,
        ),
        (
            keys::PROMPT_JUDGE_ALSO_CHANGED,
            verification::pieces::JUDGE_ALSO_CHANGED,
        ),
        (keys::PROMPT_JUDGE_DIFF, verification::pieces::JUDGE_DIFF),
        (
            keys::PROMPT_JUDGE_REFERENCES,
            verification::pieces::JUDGE_REFERENCES,
        ),
        (
            keys::PROMPT_JUDGE_GAMING_OPENING,
            verification::pieces::JUDGE_GAMING_OPENING,
        ),
        (
            keys::PROMPT_JUDGE_GAMING_BASELINE,
            verification::pieces::JUDGE_GAMING_BASELINE,
        ),
        (
            keys::PROMPT_JUDGE_GAMING_NO_BASELINE,
            verification::pieces::JUDGE_GAMING_NO_BASELINE,
        ),
        (
            keys::PROMPT_JUDGE_GAMING_HOW_TO_READ,
            verification::pieces::JUDGE_GAMING_HOW_TO_READ,
        ),
        (
            keys::PROMPT_JUDGE_GAMING_DIFF,
            verification::pieces::JUDGE_GAMING_DIFF,
        ),
        (
            keys::PROMPT_JUDGE_GAMING_QUESTION,
            verification::pieces::JUDGE_GAMING_QUESTION,
        ),
        (
            keys::PROMPT_JUDGE_GAMING_ANSWER,
            verification::pieces::JUDGE_GAMING_ANSWER,
        ),
        (
            keys::PROMPT_JUDGE_PATTERN_ASSERTION_WEAKENED,
            verification::pieces::JUDGE_PATTERN_ASSERTION_WEAKENED,
        ),
        (
            keys::PROMPT_JUDGE_PATTERN_TEST_SCOPE_NARROWED,
            verification::pieces::JUDGE_PATTERN_TEST_SCOPE_NARROWED,
        ),
        (
            keys::PROMPT_JUDGE_PATTERN_TAUTOLOGICAL_TEST,
            verification::pieces::JUDGE_PATTERN_TAUTOLOGICAL_TEST,
        ),
        (
            keys::PROMPT_JUDGE_PATTERN_NO_FINDINGS,
            verification::pieces::JUDGE_PATTERN_NO_FINDINGS,
        ),
        (
            keys::PROMPT_JUDGE_PATTERN_FINDINGS_NOT_TIED,
            verification::pieces::JUDGE_PATTERN_FINDINGS_NOT_TIED,
        ),
        (
            keys::PROMPT_JUDGE_PATTERN_FINDINGS_GENERIC,
            verification::pieces::JUDGE_PATTERN_FINDINGS_GENERIC,
        ),
        (
            keys::PROMPT_JUDGE_SECOND_OPENING,
            verification::pieces::JUDGE_SECOND_OPENING,
        ),
        (
            keys::PROMPT_JUDGE_SECOND_QUESTION,
            verification::pieces::JUDGE_SECOND_QUESTION,
        ),
        (
            keys::PROMPT_JUDGE_SECOND_CITED,
            verification::pieces::JUDGE_SECOND_CITED,
        ),
        (
            keys::PROMPT_JUDGE_SECOND_AT_LINE,
            verification::pieces::JUDGE_SECOND_AT_LINE,
        ),
        (
            keys::PROMPT_JUDGE_SECOND_REMOVED_LINE,
            verification::pieces::JUDGE_SECOND_REMOVED_LINE,
        ),
        (
            keys::PROMPT_JUDGE_SECOND_HOW_TO_WEIGH,
            verification::pieces::JUDGE_SECOND_HOW_TO_WEIGH,
        ),
        (
            keys::PROMPT_JUDGE_SECOND_ANSWER,
            verification::pieces::JUDGE_SECOND_ANSWER,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_OPENING,
            verification::pieces::JUDGE_CONVERGE_OPENING,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_DECLARED,
            verification::pieces::JUDGE_CONVERGE_DECLARED,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_OFF_PLAN,
            verification::pieces::JUDGE_CONVERGE_OFF_PLAN,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_LAST_TIME,
            verification::pieces::JUDGE_CONVERGE_LAST_TIME,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_LAST_TIME_RULE,
            verification::pieces::JUDGE_CONVERGE_LAST_TIME_RULE,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_DIFF,
            verification::pieces::JUDGE_CONVERGE_DIFF,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_WRITTEN,
            verification::pieces::JUDGE_CONVERGE_WRITTEN,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_NOTHING_WRITTEN,
            verification::pieces::JUDGE_CONVERGE_NOTHING_WRITTEN,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_TOO_BIG,
            verification::pieces::JUDGE_CONVERGE_TOO_BIG,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_NOTHING_ELSE,
            verification::pieces::JUDGE_CONVERGE_NOTHING_ELSE,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_ALONGSIDE,
            verification::pieces::JUDGE_CONVERGE_ALONGSIDE,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_QUESTION,
            verification::pieces::JUDGE_CONVERGE_QUESTION,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_CITES_DIFF,
            verification::pieces::JUDGE_CONVERGE_CITES_DIFF,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_CITES_FILE,
            verification::pieces::JUDGE_CONVERGE_CITES_FILE,
        ),
        (
            keys::PROMPT_JUDGE_CONVERGE_ANSWER,
            verification::pieces::JUDGE_CONVERGE_ANSWER,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_OPENING,
            verification::pieces::JUDGE_WIDEN_OPENING,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_STEP,
            verification::pieces::JUDGE_WIDEN_STEP,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_DELIVERABLE,
            verification::pieces::JUDGE_WIDEN_DELIVERABLE,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_HELD,
            verification::pieces::JUDGE_WIDEN_HELD,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_ASKED,
            verification::pieces::JUDGE_WIDEN_ASKED,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_FENCED,
            verification::pieces::JUDGE_WIDEN_FENCED,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_WHY,
            verification::pieces::JUDGE_WIDEN_WHY,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_QUESTION,
            verification::pieces::JUDGE_WIDEN_QUESTION,
        ),
        (
            keys::PROMPT_JUDGE_WIDEN_ANSWER,
            verification::pieces::JUDGE_WIDEN_ANSWER,
        ),
        (
            keys::PROMPT_OUTCOME_VERIFIED_ALL,
            verification::pieces::OUTCOME_VERIFIED_ALL,
        ),
        (
            keys::PROMPT_OUTCOME_VERIFIED_NONE_COVERED,
            verification::pieces::OUTCOME_VERIFIED_NONE_COVERED,
        ),
        (
            keys::PROMPT_OUTCOME_VERIFIED_SOME,
            verification::pieces::OUTCOME_VERIFIED_SOME,
        ),
        (
            keys::PROMPT_OUTCOME_ACCEPTED,
            verification::pieces::OUTCOME_ACCEPTED,
        ),
        (
            keys::PROMPT_OUTCOME_GO_ON,
            verification::pieces::OUTCOME_GO_ON,
        ),
        (
            keys::PROMPT_OUTCOME_LAST,
            verification::pieces::OUTCOME_LAST,
        ),
        (
            keys::PROMPT_OUTCOME_HANDED_BACK,
            verification::pieces::OUTCOME_HANDED_BACK,
        ),
        (
            keys::PROMPT_OUTCOME_WORK_AGAIN,
            verification::pieces::OUTCOME_WORK_AGAIN,
        ),
        (
            keys::PROMPT_BASE_UP_TO_DATE,
            verification::pieces::BASE_UP_TO_DATE,
        ),
        (
            keys::PROMPT_BASE_CONFLICTED,
            verification::pieces::BASE_CONFLICTED,
        ),
        (
            keys::PROMPT_BASE_NOT_MOVED,
            verification::pieces::BASE_NOT_MOVED,
        ),
    ]
}
